/**
 * Fixed scaffolds bundled into every theme.
 *
 * Cart and checkout are handed to WooCommerce's own blocks per the
 * architecture decision (#4) — we wrap the official blocks in our
 * header/footer template-parts and stop. The 404 is a minimal
 * site-pattern that reads on-brand. style.css is the WP theme header.
 * functions.php is the smallest viable bootstrap.
 */

import type { BlockNode } from "../pipeline/types.js";
import { serialize } from "./serializer.js";

// ── Theme header (style.css) ────────────────────────────────────────────

export interface ThemeMetadata {
  name: string;        // "Bellwether Coffee"
  slug: string;        // "bellwether-coffee" — directory name
  description: string; // 1-line tagline from brand spec
  author: string;
  authorUri?: string;
  themeUri?: string;
  version: string;     // semver, e.g. "1.0.0"
  textDomain?: string;
  tags?: string[];
}

export function buildStyleCss(meta: ThemeMetadata): string {
  const tags = meta.tags?.join(", ") ?? "block-theme, full-site-editing, woocommerce";
  return [
    "/*",
    `Theme Name: ${meta.name}`,
    meta.themeUri ? `Theme URI: ${meta.themeUri}` : null,
    `Author: ${meta.author}`,
    meta.authorUri ? `Author URI: ${meta.authorUri}` : null,
    `Description: ${meta.description}`,
    `Version: ${meta.version}`,
    "Requires at least: 6.5",
    "Tested up to: 6.7",
    "Requires PHP: 7.4",
    "License: GNU General Public License v2 or later",
    "License URI: http://www.gnu.org/licenses/gpl-2.0.html",
    `Text Domain: ${meta.textDomain ?? meta.slug}`,
    `Tags: ${tags}`,
    "*/",
    "",
  ]
    .filter((l): l is string => l !== null)
    .join("\n");
}

// ── functions.php ───────────────────────────────────────────────────────

export function buildFunctionsPhp(meta: ThemeMetadata): string {
  return [
    "<?php",
    `// ${meta.name} theme bootstrap. Generated by woo-theme-forge.`,
    "",
    "if ( ! defined( 'ABSPATH' ) ) { exit; }",
    "",
    `if ( ! function_exists( '${functionPrefix(meta.slug)}_setup' ) ) {`,
    `    function ${functionPrefix(meta.slug)}_setup() {`,
    "        add_theme_support( 'wp-block-styles' );",
    "        add_theme_support( 'editor-styles' );",
    "        add_theme_support( 'responsive-embeds' );",
    "        add_theme_support( 'align-wide' );",
    "        add_theme_support( 'post-thumbnails' );",
    "        add_theme_support( 'woocommerce' );",
    "    }",
    "}",
    `add_action( 'after_setup_theme', '${functionPrefix(meta.slug)}_setup' );`,
    "",
  ].join("\n");
}

function functionPrefix(slug: string): string {
  // PHP function names: snake_case, no leading digit.
  const sanitized = slug.replace(/[^a-z0-9_]/g, "_").replace(/^_+|_+$/g, "");
  return /^[0-9]/.test(sanitized) ? `t_${sanitized}` : sanitized || "theme";
}

// ── Template scaffolds (cart, checkout, 404) ───────────────────────────

const HEADER_PART: BlockNode = {
  name: "core/template-part",
  attrs: { slug: "header", tagName: "header" },
};

const FOOTER_PART: BlockNode = {
  name: "core/template-part",
  attrs: { slug: "footer", tagName: "footer" },
};

function wrapWithChrome(inner: BlockNode[]): string {
  const sections = [
    serialize([HEADER_PART]),
    ...inner.map((n) => serialize([n])),
    serialize([FOOTER_PART]),
  ];
  return sections.join("\n\n") + "\n";
}

/**
 * Cart template — wraps the official WooCommerce cart block in our
 * chrome. Per architecture decision #4, the cart layout itself is
 * never freestyled.
 */
export function buildCartTemplate(): string {
  const cart: BlockNode = {
    name: "core/group",
    attrs: {
      align: "full",
      tagName: "section",
      style: {
        spacing: {
          padding: {
            top: "var:preset|spacing|section",
            bottom: "var:preset|spacing|section",
          },
        },
      },
      layout: { type: "constrained" },
    },
    innerBlocks: [{ name: "woocommerce/cart" }],
  };
  return wrapWithChrome([cart]);
}

/**
 * Checkout template — same shape, but the official `woocommerce/checkout`
 * block. Same constraint.
 */
export function buildCheckoutTemplate(): string {
  const checkout: BlockNode = {
    name: "core/group",
    attrs: {
      align: "full",
      tagName: "section",
      style: {
        spacing: {
          padding: {
            top: "var:preset|spacing|section",
            bottom: "var:preset|spacing|section",
          },
        },
      },
      layout: { type: "constrained" },
    },
    innerBlocks: [{ name: "woocommerce/checkout" }],
  };
  return wrapWithChrome([checkout]);
}

/** Minimal 404 — readable, on-brand without any pattern dependencies. */
export function build404Template(): string {
  const body: BlockNode = {
    name: "core/group",
    attrs: {
      align: "full",
      tagName: "section",
      style: {
        spacing: {
          padding: {
            top: "var:preset|spacing|section",
            bottom: "var:preset|spacing|section",
          },
        },
      },
      layout: { type: "constrained", contentSize: "560px" },
    },
    innerBlocks: [
      {
        name: "core/heading",
        attrs: { level: 1, textAlign: "center", fontSize: "huge" },
        content: "Not found",
      },
      {
        name: "core/paragraph",
        attrs: { align: "center" },
        content:
          "The page you were looking for has moved or never existed. Try the shop, or use the navigation above.",
      },
      // Static button — bypasses the slot-based core/button renderer.
      // Cart/checkout/404 buttons are never customized, so we embed the
      // raw button markup via core/html instead of inventing a new
      // literal-button code path on the renderer.
      {
        name: "core/html",
        content:
          '<div class="wp-block-buttons" style="justify-content:center;display:flex"><div class="wp-block-button"><a class="wp-block-button__link has-background-color has-primary-background-color has-text-color has-background wp-element-button" href="/shop">Back to shop</a></div></div>',
      },
    ],
  };
  return wrapWithChrome([body]);
}
